name: webhook-via-github
services:
  app:
    container_name: javaApp
    image: orenv3/webhook-github:0.3
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/audit?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      db :
       condition: service_healthy


  db:
    container_name: MySql
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: audit
    ports:
      - "33061:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10